---

- name: Generate Key
  # so hangs -> cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
  shell: tr -dc _A-Z-a-z-0-9 < /dev/urandom | tail -n +1 | head -c 64
  register: command_output
